
# Los tres tipos de tarjetas:
TARJETA_COMODIN = 0
TARJETA_GALEON = 1
TARJETA_GLOBO = 2
TARJETA_CANON = 3
NOMBRE_TARJETAS = {
	TARJETA_COMODIN: 'comodin',
	TARJETA_GALEON: 'galeon',
	TARJETA_GLOBO: 'globo',
	TARJETA_CANON: 'canon',
}

# Colores de los ejercitos:
COLOR_NEGRO = 0
COLOR_AZUL = 1
COLOR_ROJO = 2
COLOR_ROSA = 3
COLOR_AMARILLO = 4
COLOR_VERDE = 5

COLORES = [COLOR_NEGRO, COLOR_AZUL, COLOR_ROJO, COLOR_ROSA, COLOR_AMARILLO, COLOR_VERDE]

NOMBRE_COLORES = {
	COLOR_NEGRO: 'negro',
	COLOR_AZUL: 'azul',
	COLOR_ROJO: 'rojo',
	COLOR_ROSA: 'rosa',
	COLOR_AMARILLO: 'amarillo',
	COLOR_VERDE: 'verde',
}

